# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore
from PyQt5.QtWidgets import *


try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:

    def _fromUtf8(s):
        return s


try:
    _encoding = QApplication.UnicodeUTF8

    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig, _encoding)


except AttributeError:

    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1024, 600)
        self.centralWidget = QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout = QGridLayout(self.centralWidget)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tableWidget = QTableWidget(self.centralWidget)
        self.tableWidget.setSelectionMode(QAbstractItemView.SingleSelection)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(14)
        self.tableWidget.setRowCount(14)
        item = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QTableWidgetItem()
        # self.tableWidget.setVerticalHeaderItem(14, item)
        # item = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        # item = QTableWidgetItem()
        # self.tableWidget.setHorizontalHeaderItem(14, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(0, 5, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(0, 6, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(0, 7, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(0, 8, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(0, 9, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(0, 10, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(0, 11, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(0, 12, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(0, 13, item)
        # item = QTableWidgetItem()
        #         # self.tableWidget.setItem(0, 14, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(1, 4, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(1, 5, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(1, 6, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(1, 7, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(1, 8, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(1, 9, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(1, 10, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(1, 11, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(1, 12, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(1, 13, item)
        # item = QTableWidgetItem()
        #         # self.tableWidget.setItem(1, 14, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(2, 4, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(2, 5, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(2, 6, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(2, 7, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(2, 8, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(2, 9, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(2, 10, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(2, 11, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(2, 12, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(2, 13, item)
        # item = QTableWidgetItem()
        #         # self.tableWidget.setItem(2, 14, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(3, 3, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(3, 4, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(3, 5, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(3, 6, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(3, 7, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(3, 8, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(3, 9, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(3, 10, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(3, 11, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(3, 12, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(3, 13, item)
        # item = QTableWidgetItem()
        #         # self.tableWidget.setItem(3, 14, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(4, 3, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(4, 4, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(4, 5, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(4, 6, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(4, 7, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(4, 8, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(4, 9, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(4, 10, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(4, 11, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(4, 12, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(4, 13, item)
        # item = QTableWidgetItem()
        #         # self.tableWidget.setItem(4, 14, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(5, 2, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(5, 3, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(5, 4, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(5, 5, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(5, 6, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(5, 7, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(5, 8, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(5, 9, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(5, 10, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(5, 11, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(5, 12, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(5, 13, item)
        # item = QTableWidgetItem()
        #         # self.tableWidget.setItem(5, 14, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(6, 1, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(6, 2, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(6, 3, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(6, 4, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(6, 5, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(6, 6, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(6, 7, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(6, 8, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(6, 9, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(6, 10, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(6, 11, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(6, 12, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(6, 13, item)
        # item = QTableWidgetItem()
        #         # self.tableWidget.setItem(6, 14, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(7, 1, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(7, 2, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(7, 3, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(7, 4, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(7, 5, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(7, 6, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(7, 7, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(7, 8, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(7, 9, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(7, 10, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(7, 11, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(7, 12, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(7, 13, item)
        # item = QTableWidgetItem()
        #         # self.tableWidget.setItem(7, 14, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(8, 1, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(8, 2, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(8, 3, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(8, 4, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(8, 5, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(8, 6, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(8, 7, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(8, 8, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(8, 9, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(8, 10, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(8, 11, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(8, 12, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(8, 13, item)
        # item = QTableWidgetItem()
        #         # self.tableWidget.setItem(8, 14, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(9, 1, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(9, 2, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(9, 3, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(9, 4, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(9, 5, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(9, 6, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(9, 7, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(9, 8, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(9, 9, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(9, 10, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(9, 11, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(9, 12, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(9, 13, item)
        # item = QTableWidgetItem()
        #         # self.tableWidget.setItem(9, 14, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(10, 0, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(10, 1, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(10, 2, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(10, 3, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(10, 4, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(10, 5, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(10, 6, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(10, 7, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(10, 8, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(10, 9, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(10, 10, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(10, 11, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(10, 12, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(10, 13, item)
        # item = QTableWidgetItem()
        #         # self.tableWidget.setItem(10, 14, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(11, 0, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(11, 1, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(11, 2, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(11, 3, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(11, 4, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(11, 5, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(11, 6, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(11, 7, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(11, 8, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(11, 9, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(11, 10, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(11, 11, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(11, 12, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(11, 13, item)
        # item = QTableWidgetItem()
        #         # self.tableWidget.setItem(11, 14, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(12, 0, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(12, 1, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(12, 2, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(12, 3, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(12, 4, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(12, 5, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(12, 6, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(12, 7, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(12, 8, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(12, 9, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(12, 10, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(12, 11, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(12, 12, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(12, 13, item)
        # item = QTableWidgetItem()
        # self.tableWidget.setItem(12, 14, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(13, 0, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(13, 1, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(13, 2, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(13, 3, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(13, 4, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(13, 5, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(13, 6, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(13, 7, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(13, 8, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(13, 9, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(13, 10, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(13, 11, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(13, 12, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(13, 13, item)
        # item = QTableWidgetItem()
        #         # self.tableWidget.setItem(13, 14, item)
        #         # item = QTableWidgetItem()
        #         # self.tableWidget.setItem(14, 0, item)
        #         # item = QTableWidgetItem()
        #         # self.tableWidget.setItem(14, 1, item)
        #         # item = QTableWidgetItem()
        #         # self.tableWidget.setItem(14, 2, item)
        #         # item = QTableWidgetItem()
        #         # self.tableWidget.setItem(14, 3, item)
        #         # item = QTableWidgetItem()
        #         # self.tableWidget.setItem(14, 4, item)
        #         # item = QTableWidgetItem()
        #         # self.tableWidget.setItem(14, 5, item)
        #         # item = QTableWidgetItem()
        #         # self.tableWidget.setItem(14, 6, item)
        #         # item = QTableWidgetItem()
        #         # self.tableWidget.setItem(14, 7, item)
        #         # item = QTableWidgetItem()
        #         # self.tableWidget.setItem(14, 8, item)
        #         # item = QTableWidgetItem()
        #         # self.tableWidget.setItem(14, 9, item)
        #         # item = QTableWidgetItem()
        #         # self.tableWidget.setItem(14, 10, item)
        #         # item = QTableWidgetItem()
        #         # self.tableWidget.setItem(14, 11, item)
        #         # item = QTableWidgetItem()
        #         # self.tableWidget.setItem(14, 12, item)
        #         # item = QTableWidgetItem()
        #         # self.tableWidget.setItem(14, 13, item)
        #         # item = QTableWidgetItem()
        #         # self.tableWidget.setItem(14, 14, item)

        self.openLineEdit = QLineEdit(self.centralWidget)
        self.openLineEdit.setMinimumSize(QtCore.QSize(90, 20))
        self.openLineEdit.setObjectName(_fromUtf8("openLineEdit"))
        self.gridLayout.addWidget(self.openLineEdit, 0, 1, 1, 3)

        self.openButton = QPushButton(self.centralWidget)
        self.openButton.setMinimumSize(QtCore.QSize(30, 30))
        self.openButton.setObjectName(_fromUtf8("openButton"))
        self.gridLayout.addWidget(self.openButton, 0, 0, 1, 1)

        self.gridLayout.addWidget(self.tableWidget, 2, 1, 4, 1)
        self.buildButton = QPushButton(self.centralWidget)
        self.buildButton.setMinimumSize(QtCore.QSize(90, 50))
        self.buildButton.setObjectName(_fromUtf8("buildButton"))
        self.gridLayout.addWidget(self.buildButton, 2, 0, 1, 1)
        self.label = QTextBrowser(self.centralWidget)
        self.label.setAutoFillBackground(True)
        # self.label.setStyleSheet("QLabel { background-color : #ffffff;}")
        self.label.setMinimumSize(QtCore.QSize(0, 100))
        self.label.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label.setAlignment(QtCore.Qt.AlignLeft)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 6, 1, 1, 1)
        self.researchButton = QPushButton(self.centralWidget)
        self.researchButton.setMinimumSize(QtCore.QSize(90, 50))
        self.researchButton.setObjectName(_fromUtf8("researchButton"))
        self.gridLayout.addWidget(self.researchButton, 6, 0, 1, 1)
        self.addButton = QPushButton(self.centralWidget)
        self.addButton.setObjectName(_fromUtf8("addButton"))
        self.gridLayout.addWidget(self.addButton, 3, 0, 1, 1)
        self.removeButton = QPushButton(self.centralWidget)
        self.removeButton.setObjectName(_fromUtf8("removeButton"))
        self.gridLayout.addWidget(self.removeButton, 4, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.buildButton.clicked.connect(MainWindow.buildClicked)
        self.researchButton.clicked.connect(MainWindow.researchClicked)
        self.addButton.clicked.connect(MainWindow.addClicked)
        self.removeButton.clicked.connect(MainWindow.removeClicked)
        self.openButton.clicked.connect(MainWindow.openClicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))

        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8", None))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9", None))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10", None))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "11", None))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12", None))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13", None))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "14", None))
        # item = self.tableWidget.verticalHeaderItem(14)
        # item.setText(_translate("MainWindow", "15", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "8", None))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "9", None))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "10", None))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "11", None))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "12", None))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "13", None))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "14", None))
        # # item = self.tableWidget.horizontalHeaderItem(14)
        # item.setText(_translate("MainWindow", "15", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "0.3", None))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("MainWindow", "0.6", None))
        item = self.tableWidget.item(0, 5)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(0, 6)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(0, 7)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(0, 8)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(0, 9)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(0, 10)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(0, 11)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(0, 12)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(0, 13)
        item.setText(_translate("MainWindow", "0", None))
        # item = self.tableWidget.item(0, 14)
        # item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(1, 4)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(1, 5)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(1, 6)
        item.setText(_translate("MainWindow", "0.1", None))
        item = self.tableWidget.item(1, 7)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(1, 8)
        item.setText(_translate("MainWindow", "0.2", None))
        item = self.tableWidget.item(1, 9)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(1, 10)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(1, 11)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(1, 12)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(1, 13)
        item.setText(_translate("MainWindow", "0", None))
        # item = self.tableWidget.item(1, 14)
        # item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("MainWindow", "0.6", None))
        item = self.tableWidget.item(2, 4)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(2, 5)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(2, 6)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(2, 7)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(2, 8)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(2, 9)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(2, 10)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(2, 11)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(2, 12)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(2, 13)
        item.setText(_translate("MainWindow", "0", None))
        # item = self.tableWidget.item(2, 14)
        # item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(3, 3)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(3, 4)
        item.setText(_translate("MainWindow", "0.4", None))
        item = self.tableWidget.item(3, 5)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(3, 6)
        item.setText(_translate("MainWindow", "-0.1", None))
        item = self.tableWidget.item(3, 7)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(3, 8)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(3, 9)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(3, 10)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(3, 11)
        item.setText(_translate("MainWindow", "0.3", None))
        item = self.tableWidget.item(3, 12)
        item.setText(_translate("MainWindow", "0.8", None))
        item = self.tableWidget.item(3, 13)
        item.setText(_translate("MainWindow", "0", None))
        # item = self.tableWidget.item(3, 14)
        # item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("MainWindow", "0.2", None))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(4, 3)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(4, 4)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(4, 5)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(4, 6)
        item.setText(_translate("MainWindow", "-0.1", None))
        item = self.tableWidget.item(4, 7)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(4, 8)
        item.setText(_translate("MainWindow", "0.3", None))
        item = self.tableWidget.item(4, 9)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(4, 10)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(4, 11)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(4, 12)
        item.setText(_translate("MainWindow", "0.3", None))
        item = self.tableWidget.item(4, 13)
        item.setText(_translate("MainWindow", "0", None))
        # item = self.tableWidget.item(4, 14)
        # item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("MainWindow", "0.4", None))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(5, 2)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(5, 3)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(5, 4)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(5, 5)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(5, 6)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(5, 7)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(5, 8)
        item.setText(_translate("MainWindow", "0.3", None))
        item = self.tableWidget.item(5, 9)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(5, 10)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(5, 11)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(5, 12)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(5, 13)
        item.setText(_translate("MainWindow", "0", None))
        # item = self.tableWidget.item(5, 14)
        # item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(6, 1)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(6, 2)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(6, 3)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(6, 4)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(6, 5)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(6, 6)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(6, 7)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(6, 8)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(6, 9)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(6, 10)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(6, 11)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(6, 12)
        item.setText(_translate("MainWindow", "0.3", None))
        item = self.tableWidget.item(6, 13)
        item.setText(_translate("MainWindow", "0", None))
        # item = self.tableWidget.item(6, 14)
        # item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("MainWindow", "0.3", None))
        item = self.tableWidget.item(7, 1)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(7, 2)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(7, 3)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(7, 4)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(7, 5)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(7, 6)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(7, 7)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(7, 8)
        item.setText(_translate("MainWindow", "0.6", None))
        item = self.tableWidget.item(7, 9)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(7, 10)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(7, 11)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(7, 12)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(7, 13)
        item.setText(_translate("MainWindow", "0", None))
        # item = self.tableWidget.item(7, 14)
        # item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(8, 1)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(8, 2)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(8, 3)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(8, 4)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(8, 5)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(8, 6)
        item.setText(_translate("MainWindow", "-0.2", None))
        item = self.tableWidget.item(8, 7)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(8, 8)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(8, 9)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(8, 10)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(8, 11)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(8, 12)
        item.setText(_translate("MainWindow", "0.1", None))
        item = self.tableWidget.item(8, 13)
        item.setText(_translate("MainWindow", "0", None))
        # item = self.tableWidget.item(8, 14)
        # item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("MainWindow", "0.6", None))
        item = self.tableWidget.item(9, 1)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(9, 2)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(9, 3)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(9, 4)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(9, 5)
        item.setText(_translate("MainWindow", "0.7", None))
        item = self.tableWidget.item(9, 6)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(9, 7)
        item.setText(_translate("MainWindow", "0.3", None))
        item = self.tableWidget.item(9, 8)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(9, 9)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(9, 10)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(9, 11)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(9, 12)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(9, 13)
        item.setText(_translate("MainWindow", "0", None))
        # item = self.tableWidget.item(9, 14)
        # item.setText(_translate("MainWindow", "0.6", None))
        item = self.tableWidget.item(10, 0)
        item.setText(_translate("MainWindow", "0.1", None))
        item = self.tableWidget.item(10, 1)
        item.setText(_translate("MainWindow", "0.2", None))
        item = self.tableWidget.item(10, 2)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(10, 3)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(10, 4)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(10, 5)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(10, 6)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(10, 7)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(10, 8)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(10, 9)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(10, 10)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(10, 11)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(10, 12)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(10, 13)
        item.setText(_translate("MainWindow", "0", None))
        # item = self.tableWidget.item(10, 14)
        # item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(11, 0)
        item.setText(_translate("MainWindow", "0.3", None))
        item = self.tableWidget.item(11, 1)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(11, 2)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(11, 3)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(11, 4)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(11, 5)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(11, 6)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(11, 7)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(11, 8)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(11, 9)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(11, 10)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(11, 11)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(11, 12)
        item.setText(_translate("MainWindow", "0.6", None))
        item = self.tableWidget.item(11, 13)
        item.setText(_translate("MainWindow", "0", None))
        # item = self.tableWidget.item(11, 14)
        # item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(12, 0)
        item.setText(_translate("MainWindow", "0.2", None))
        item = self.tableWidget.item(12, 1)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(12, 2)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(12, 3)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(12, 4)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(12, 5)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(12, 6)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(12, 7)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(12, 8)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(12, 9)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(12, 10)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(12, 11)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(12, 12)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(12, 13)
        item.setText(_translate("MainWindow", "0", None))
        # item = self.tableWidget.item(12, 14)
        # item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(13, 0)
        item.setText(_translate("MainWindow", "-0.1", None))
        item = self.tableWidget.item(13, 1)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(13, 2)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(13, 3)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(13, 4)
        item.setText(_translate("MainWindow", "-0.1", None))
        item = self.tableWidget.item(13, 5)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(13, 6)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(13, 7)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(13, 8)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(13, 9)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(13, 10)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(13, 11)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(13, 12)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget.item(13, 13)
        item.setText(_translate("MainWindow", "0", None))
        # item = self.tableWidget.item(13, 14)
        # item.setText(_translate("MainWindow", "0", None))
        # item = self.tableWidget.item(14, 0)
        # item.setText(_translate("MainWindow", "0.2", None))
        # item = self.tableWidget.item(14, 1)
        # item.setText(_translate("MainWindow", "0", None))
        # item = self.tableWidget.item(14, 2)
        # item.setText(_translate("MainWindow", "0", None))
        # item = self.tableWidget.item(14, 3)
        # item.setText(_translate("MainWindow", "0.4", None))
        # item = self.tableWidget.item(14, 4)
        # item.setText(_translate("MainWindow", "0.4", None))
        # item = self.tableWidget.item(14, 5)
        # item.setText(_translate("MainWindow", "0", None))
        # item = self.tableWidget.item(14, 6)
        # item.setText(_translate("MainWindow", "0", None))
        # item = self.tableWidget.item(14, 7)
        # item.setText(_translate("MainWindow", "0.1", None))
        # item = self.tableWidget.item(14, 8)
        # item.setText(_translate("MainWindow", "0", None))
        # item = self.tableWidget.item(14, 9)
        # item.setText(_translate("MainWindow", "0", None))
        # item = self.tableWidget.item(14, 10)
        # item.setText(_translate("MainWindow", "0", None))
        # item = self.tableWidget.item(14, 11)
        # item.setText(_translate("MainWindow", "0", None))
        # item = self.tableWidget.item(14, 12)
        # item.setText(_translate("MainWindow", "0.4", None))
        # item = self.tableWidget.item(14, 13)
        # item.setText(_translate("MainWindow", "0", None))
        # item = self.tableWidget.item(14, 14)
        # item.setText(_translate("MainWindow", "0", None))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.openButton.setText(_translate("MainWindow", "Open", None))
        self.buildButton.setText(_translate("MainWindow", "Build graph", None))
        self.label.setText(_translate("MainWindow", "", None))
        self.openLineEdit.setText(_translate("MainWindow", "data/sample_data.csv", None))
        self.researchButton.setText(_translate("MainWindow", "Research", None))
        self.addButton.setText(_translate("MainWindow", "+", None))
        self.removeButton.setText(_translate("MainWindow", "-", None))
